### ISSUE TITLE
Ability to start servers independently

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/kazana#1]
@gr2m explained to me that a single server can be started in bare mode via
```sh
$ kazana --bare node_modules/kazana-raw-data
```

For deployment we need a way to start all servers independently, for monitoring purposes. The question is: how can we know about each server and where it lives?

For example if I include kazana in a project and add a plugin `send-daily-email-report`, which lives at `./node_modules/send-daily-email-report`, I need a way to list it. This could be an option to the kazana bin, eg:

```sh
$ ./node_modules/.bin/kazana --list-plugins
./node_modules/send-daily-email-report
./node_modules/kazana/node_modules/send-daily-email-report
```

Then each line of the output could be feeded to the `kazana` bin as `--bare` option.

**Comment by jo** [comment]
We can include information about the services in _package.json_, eg
```json
  },
  "services": {
    "accounts": {},
    "importer": {},
    "indices": {},
    "normaliser": {},
    "entities": {},
    "validator": {}
  },
```

**Comment by gr2m** [comment]
yeah, I wanted to add that, too. Let's do `"kazana"` instead of `"services"` though

```json
  },
  "services": {
    "accounts": {},
    "importer": {},
    "indices": {},
    "normaliser": {},
    "entities": {},
    "validator": {}
  },
```

**Comment by jo** [comment]
+1 for `kazana` namespace. Maybe even
```json
  "kazana": {
    "services": {
      "account": {},
      "raw-data": {},
      "my-custom-plugin": {}
    },
    "mode": "lazy"
  }
```

**Comment by gr2m** [comment]
What is `"mode"` for?

**Comment by jo** [comment]
just a `reserved option`

**Comment by gr2m** [comment]
We have this now in [kazana-example](https://github.com/eHealthAfrica/kazana-example)

```
$ npm run services -s
npm start -- --only=account
npm start -- --only=raw-data
npm start -- --bare
```

Does that work?

I'm thinking we still could do a bit better, to have a `kazana` CLI tool, doing things like `kazana start` to start the entire app` or `kazana start account` / `kazana start raw-data` / `kazana start app`. Then we could have `kazana list services` which would do what `npm run services -s` does right now. And ideally we'd have `kazana new <appname>` like Hoodie has it. But that's just an idea. 

I think I'm going off-topic here, sorry for that

**Comment by jo** [comment]
Isn't there a `kazana` CLI tool already?
An idea I discussed with Stephan

**Comment by jo** [comment]
That way we maybe could reduce the overhead of the npm binary, which makes things a little slow.

**Comment by boennemann** [comment]
`npm explore <package> -- <command>` let's you execute an arbitrary command in the environment of the specified dependency. That way the kazana CLI could just call e.g. `npm start` for it's plugins.

**Comment by jo** [comment]
`npm explore` might also be available programmatically, right?

**Comment by boennemann** [comment]
If you mean `require`ing npm, then yes :)

**Comment by jo** [comment]
yes, thats what I meant :)

**Comment by gr2m** [comment]
You lost me here to be honest, anyone want to start a PR for this?

**Comment by jo** [comment]
I think we can close this as we have `kazana-services`. Lets reopen if needed ;)
