### ISSUE TITLE
Deployment strategy for kazana apps

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#10]
Related to #1

**Comment by gr2m** [comment]
To sum up what we discussed with @boennemann & @janl

1. Kazana apps, unless very simple like the [example app](https://github.com/eHealthAfrica/kazana-example), don't have own code, but pull together code from other plugins. 
2. Kazana apps have CI tests, when they pass, a new version is released to npm, via [semantic-release](http://github.com/semantic-release/semantic-release) (public or private, depending on app).
3. All app-specific plugins are released continuously via semantic-release. Whenever an app-specific plugin gets released, it updates the package.json of the app with according commits (on travis), which then kicks of the release of the kazana app. If CI tests pass, a new version gets released. If it fails, it's breaking change, which needs a dedicated commit to the app, including adaption of the CI tests.
4. The app release is always tagged with `next`, and always bundles all its dependencies.

Open questions

- how are `latest` / `next` npm tags working?
- All `next` releases are continuously deployed to a staging environment
- Whenever we think it's a good time, we release a new `stable` tagged release of the
- All `stable` releases are continuously deployed to production.

@boennemann @janl Does that sound right so far?

**Comment by boennemann** [comment]
> how are latest / next npm tags working?

For changing the release channel of semantic-release you just add a `"publishConfig": {"tag": "next"}` entry to the package.json. That's npm's own way of overwriting settings at publish time, and semantic-release respects it as well. There is one caveat though, if you're having something different than "latest" you have to manually tag the first version you want start the channel off of. (This will improve somehow in the future). Other than that run `npm help dist-tag` for detailed information.

> All next releases are continuously deployed to a staging environment
Whenever we think it's a good time, we release a new stable tagged release of the
All stable releases are continuously deployed to production.

Sounds good!

**Comment by patriciagarcia** [comment]
@gr2m, can we close this ticket?

**Comment by gr2m** [comment]
yes
