### ISSUE TITLE
update kazan to node @ 4

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana#102]
- [x] kazan-config
- [x] kazana-bootstrap
- [x] kazana-raw-data
- [x] kazana-account
- [x] kazana-server
- [x] kazana
- [x] kazana-integration-test
- [x] kazana-example

**Comment by patriciagarcia** [comment]
@gr2m, this is done already, right? https://github.com/eHealthAfrica/kazana/blob/master/package.json#L35
