### ISSUE TITLE
Raw data upload response includes base64 encoded attachment, is too big

### ISSUE THREAD

**Issue by lucidNTR** [eHealthAfrica/kazana#108]

**Comment by lucidNTR** [comment]
started

**Comment by lucidNTR** [comment]
@jo 
the problem is pouchdb-hoodie-api
which is planned to be removed anyways and that does nothing to my knowledge.
is it possible to just use plain pouchdb in kazana instead?

**Comment by jo** [comment]
Yes this is possible, and I'm also in favor of this change.
But this needs to be carefully planned because that will be a breaking change and also requires a lot of changes throughout kazana.

**Comment by jo** [comment]
By now I'd suggest you just wrap the response and remove the attachment data. Or simply reload the object.

**Comment by lucidNTR** [comment]
ok will do the workaround

**Comment by lucidNTR** [comment]
probably better if you do the proper change, as you know best what the overall effect is
