### ISSUE TITLE
Remove deprecated features/APIs on next release (9.x)

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#113]
- [ ] [Use `public` instead of `static` on the config](https://github.com/eHealthAfrica/kazana-server/pull/72/files). Background [here](https://github.com/eHealthAfrica/kazana/issues/82)

**Comment by patriciagarcia** [comment]
@gr2m, @jo, I think this is the only deprecated issue for now, but feel free to add any other that you know of. 

My idea is that we can keep this  up to date and whenever we need to release a major new version (9.x) in this case, we go to this ticket and make sure to delete all deprecated features/APIs before releasing. This way we can keep the code clean without causing too much trouble to other projects.

What do you think?

**Comment by gr2m** [comment]
I think we don't need a dedicated issue for that, I'm sure we will forget to keep updated earlier or later. Instead, if we always log a 'deprecation' warning, then we can do a global find in a repo for `'deprecation'`, and it will show them all. Should be straight forward. What we could do is to document this somewhere as a step when doing major releases?

**Comment by patriciagarcia** [comment]
oh, it's fine, maybe it's not so important either way. If we forget to remove deprecated features when creating a new major release we can always remove it in the following one ;).

Oki, closing this.
