### ISSUE TITLE
Bootstrapping _users docs ends active sessions on server restart

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana#126]
follow up for https://github.com/eHealthAfrica/kazana/issues/115#issuecomment-157485024

CouchDB session IDs (this is what becomes the bearer token in kazana land) are calculated from the `_users` doc password hash, salt, and CouchDB's secret (`couch_httpd_auth.secret` config). 

If an app bootstraps test-users, it currently overrides the existing user docs, even if the password did not change. That generates a new salt, which invalidates all existing sessions for that user.

To resolve the issue, we need to be smarter of how we update existing `_users` docs. @jo created an issue for that here: https://github.com/jo/couchdb-push/issues/25. Ones that lands, this issue will be resolved in Kazana

**Comment by jo** [comment]
This is done
