### ISSUE TITLE
kazana 8.4.0 breaks van CD

### ISSUE THREAD

**Issue by lucidNTR** [eHealthAfrica/kazana#134]
(last running version was van 1.10.4)

Error: Cannot find module 'rc'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/opt/app/node_modules/@ehealthafrica/van/node_modules/kazana/node_modules/kazana-server/node_modules/kazana-config/index.js:4:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
module.js:339
    throw err;
    ^
```

​[3:28] 
this build triggered v1.10.5: https://travis-ci.com/eHealthAfrica/van/builds/18146260

​[3:28] 
https://github.com/eHealthAfrica/van/pull/227/files

**Comment by patriciagarcia** [comment]
@lucidNTR can you post a link to the failing build? (I am assuming this is in Travis)

**Comment by lucidNTR** [comment]
@patriciagarcia no the actual docker deployment fails

**Comment by lucidNTR** [comment]
i could reproduce this locally in my dev docker image

**Comment by patriciagarcia** [comment]
:+1: thanks!

**Comment by lucidNTR** [comment]
i managed to get it to start by manually installing

npm install couchdb-bootstrap
npm install nano
npm install rc

probably just a minor package.json fuckup in kazana?

**Comment by lucidNTR** [comment]
travis succeeded by the way, so its important to test the setup in docker before any merge. i prepared an updated review process recomedation to be discussed later

**Comment by jo** [comment]
Why do you think kazana 8.4.0 breaks the build?

**Comment by lucidNTR** [comment]
because it is the only change in the PR right? and it worked on the deployment before that

**Comment by jo** [comment]
Asuming the deployment did not change

**Comment by lucidNTR** [comment]
true. but good point. it my be something else

**Comment by jo** [comment]
We have confirmed that the problem does not occur in kazana 8.3.0.

**Comment by jo** [comment]
Worth to mention: The bug occurs on *startup*, not during install:
```sh
$ node_modules/\@ehealthafrica/van/node_modules/kazana/bin/server --bare --port=5000 --main=./node_modules/\@ehealthafrica/van/index.js --backend.name=couchdb --backend.location=http://localhost:5985
module.js:339
    throw err;
    ^

Error: Cannot find module 'rc'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/private/tmp/van/node_modules/@ehealthafrica/van/node_modules/kazana/node_modules/kazana-server/node_modules/kazana-config/index.js:4:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by jo** [comment]
I updated kazana-example to use kazana@8.4.0 and kazana-integration-test to use that new kazana-example and the build passes: https://github.com/eHealthAfrica/kazana-integration-test/pull/25

The difference here is that its still [based on npm3](https://travis-ci.org/eHealthAfrica/kazana-integration-test/jobs/93336178#L121)

**Comment by jo** [comment]
New build matching our environment: https://travis-ci.org/eHealthAfrica/kazana-integration-test/builds/93338273

**Comment by jo** [comment]
OK, here we go: https://travis-ci.org/eHealthAfrica/kazana-integration-test/jobs/93338275#L345-L355

The error is now showing up in travis.

**Comment by jo** [comment]
npm@2: failure
npm@2.14.13: failure
npm@3: pass

**Comment by obdulia-losantos** [comment]
`kazana-transform` still requires `npm@3` 
https://github.com/eHealthAfrica/kazana-transform/blob/master/package.json#L17-L18

**Comment by jo** [comment]
good catch!

**Comment by jo** [comment]
So the problem traces down to kazana-transform. Here is a failing build: https://travis-ci.org/eHealthAfrica/kazana-transform/builds/93345930#L212-L222

**Comment by jo** [comment]
npm@2 installs the following rc packages:
```
root@45bc72330cf4:~/kazana-transform# find node_modules/ -name rc
node_modules/standard/node_modules/standard-format/node_modules/esformatter/test/compare/rc
node_modules/standard/node_modules/standard-format/node_modules/esformatter/test/compare/rc/package/rc
node_modules/standard/node_modules/standard-format/rc
node_modules/standard/rc
node_modules/kazana-server/node_modules/pouchdb-authentication/node_modules/pouchdb/node_modules/leveldown/node_modules/prebuild/node_modules/.bin/rc
node_modules/kazana-server/node_modules/pouchdb-authentication/node_modules/pouchdb/node_modules/leveldown/node_modules/prebuild/node_modules/rc
node_modules/kazana-server/node_modules/pouchdb/node_modules/leveldown/node_modules/prebuild/node_modules/.bin/rc
node_modules/kazana-server/node_modules/pouchdb/node_modules/leveldown/node_modules/prebuild/node_modules/rc
```

```
root@45bc72330cf4:~/kazana-transform# npm ls
...

npm ERR! missing: couchdb-bootstrap@1.10.4, required by kazana-bootstrap@2.1.0
npm ERR! missing: moment@2.10.6, required by kazana-bootstrap@2.1.0
npm ERR! missing: nano@6.1.5, required by kazana-bootstrap@2.1.0
npm ERR! missing: rc@^1.1.2, required by kazana-config@5.3.0
```

**Comment by jo** [comment]
While on npm3 we have
```
[jo@jolap kazana-transform]$ find node_modules/ -name rc
node_modules/standard/rc
node_modules/.bin/rc
node_modules/rc
node_modules/esformatter/test/compare/rc
node_modules/esformatter/test/compare/rc/package/rc
node_modules/standard-format/rc
```

**Comment by jo** [comment]
We have a hotfix in package.json deployed. Continue with https://github.com/eHealthAfrica/kazana/issues/140
