### ISSUE TITLE
[epic] Improve example app

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#142]
### Taks

- [ ] [Upload files](https://github.com/eHealthAfrica/kazana-example/issues/26)
- [ ] [Use different plugins](https://github.com/eHealthAfrica/kazana-example/issues/14)

**Comment by patriciagarcia** [comment]
Nothing else comes to mind right now, any other ideas @jo, @gr2m @readevalprint?

**Comment by ehealth-waffle** [comment]
closing this epic in favor of 
https://github.com/eHealthAfrica/kazana-example/issues/26 & https://github.com/eHealthAfrica/kazana-example/issues/14
