### ISSUE TITLE
[configurable indices] Make possible to combine indices (design docs) with thresholds in app-specific routes

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#155]
Related https://github.com/eHealthAfrica/kazana-entities/issues/9

**Comment by gr2m** [comment]
with thresholds from custom entities

**Comment by ehealth-waffle** [comment]
closing in favor of  #9. Isn’t it the same? @patriciagarcia

**Comment by patriciagarcia** [comment]
I assume you mean https://github.com/eHealthAfrica/kazana-entities/issues/9 and not #9? I guess some of the work should be done in the entities part and some in kazana part, but I might very possibly be wrong ;-)
