### ISSUE TITLE
Add changes feed on integrated-data

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/kazana#182]
We've a use case whereby we'd like to know when [kazana-email-box](https://github.com/eHealthAfrica/kazana-email-box) documents have been transformed (end up in `kazana-integrated-data`) so as to notify the user on the frontend (https://github.com/eHealthAfrica/van/issues/241) (right now, we're mocking this with a timeout).

Subscribing to "real" progress notifications from a transformer would be great, but seems tricky. Another approach may be to add the ability to observe particular DBs via a `_changes`-like API.

**Comment by jo** [comment]
This will be in `kazana-raw-data`.

Proposed route:
`GET /api/submissions/{id}/updates`

This will return a JSON when the document `{id}` has been transformed. If it has not been processed the connection will stay open (longpoll) until processing finished.

An example response could be
```json
{
  "id": "mydoc",
  "transformedAt": "the date",
  "transformationErrors": "omg there was an error"
}
```

**Comment by tlvince** [comment]
:+1:

**Comment by jo** [comment]
done in https://github.com/eHealthAfrica/kazana-transform-listener

**Comment by gr2m** [comment]
@jo great job!!!!
