### ISSUE TITLE
server.stop calls callback before pouchdb server freed its port

### ISSUE THREAD

**Issue by lucidNTR** [eHealthAfrica/kazana#201]
on a kazana test setup with pouchdb server and memory backend
start kazana and then

call 
```
server.stop(function () {
// do something to try to reasign the pouchdb server port or check if it was successfully freed
})
```

result: the port is not freed until ~ 1 second after the callback is called

expected: the callback is called after the pouchdb server was fully shutdown including freeing its port

**Comment by karl-ehealth** [comment]
I've seen this when im bootstrapping a lot of stuff in the tests. Wonder if it has to do with the VM you're running VAN in being slow. Not saying its not a bug, just trying to suggest some things to reproduce more easily.

**Comment by lucidNTR** [comment]
i ran into this here:
https://github.com/eHealthAfrica/kazana-raw-data/blob/fix/do_not_return_attachment_data/tests/integration/attachments/add-test.js#L48

**Comment by lucidNTR** [comment]
i ran the tests on max os x

**Comment by karl-ehealth** [comment]
sounds like you have a better way of reproducing than me :)

**Comment by jo** [comment]
Works for me. I'll remove that timeout and try again.

**Comment by jo** [comment]
To be more precise: the tests of the master branch works for me. I'm now running the tests against you branch.

**Comment by jo** [comment]
They also pass. I now remove the timeout...

**Comment by jo** [comment]
Tests still pass. Cannot reproduce. Please reopen with more info about how this can be reproduced.

**Comment by lucidNTR** [comment]
seems to need os x! it seems to be happening due to different socket closing timing in node on os x

- yes, all errors are my iPhone's fault

**Comment by jo** [comment]
Does it also happen on the master branch?

**Comment by jo** [comment]
Also this should not rely on the right timing.
