### ISSUE TITLE
dbs option

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/kazana#202]
We need a way to configure databases introduced by plugins. The main use case is to make them available for `server.methods.getStore()`.

This method does a lookup for configured database names, eg you can specify for the internal database 'raw-data` a different name:

```js
{
  config: {
    kazana: {
      db: {
        rawData: 'my-special-configured-database-name-for-kazana-raw-data'
      }
    }
  }
}
```

I propose to add a `dbs` toplevel configuration option for kazana plugins where you specify in an array the databases for your plugin.

For the `kazana-email-box` plugin this could look like this:

```js
{
  name: 'kazana-email-box',
  dbs: ['emailBox'],
  config: {
    'kazana-email-box': {
      db: {
        emailBox: 'kazana-email-box'
      }
    }
  }
}
```

**Comment by lucidNTR** [comment]
@jo ok should i implement ?

**Comment by jo** [comment]
One point where I'm uncertain about it the use of `emailBox` identifier versus `email-box`.

**Comment by lucidNTR** [comment]
we should just use underscores for everythig, then problems like that dont happen :-P

**Comment by lucidNTR** [comment]
so should i implement or you? @jo

**Comment by jo** [comment]
Yes go ahead!

**Comment by lucidNTR** [comment]
done in kazana-server pr #135

**Comment by jo** [comment]
The pull you referenced is not the one which resolves this issue

**Comment by lucidNTR** [comment]
https://github.com/eHealthAfrica/kazana-server/pull/135
