### ISSUE TITLE
Bundled kazana-* packages are wrong

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana#36]
defined in package.json right now is

```
   "kazana-account": "2.0.0",
    "kazana-raw-data": "3.1.0",
    "kazana-server": "1.2.0",
```

But when doing npm install I see

```
$ cat node_modules/kazana/node_modules/kazana-account/package.json | grep version
  "version": "2.0.0",
$ cat node_modules/kazana/node_modules/kazana-raw-data/package.json | grep version
  "version": "3.0.0",
$ cat node_modules/kazana/node_modules/kazana-server/package.json | grep version
  "version": "1.0.0",
```

Any idea why that is? Can you fix that @boennemann? We had it before, back then I commited an empty fix commit and it seems to have resolved the issue, but would be good if we somehow could prevent that from happening

**Comment by gr2m** [comment]
@boennemann this is resolved now, via https://www.npmjs.com/package/dynamic-bundle, right?

**Comment by boennemann** [comment]
Right :)
