### ISSUE TITLE
Ability to increase spawnPouchdbServer timeout

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/kazana#45]
Starting kazana newly often fails with a timeout error:

```
[jo@jolap myapp]$ npm start

> myapp@1.2.0 start van
> kazana

backend.location not set, starting PouchDB Server at 4999 ...
kazana/bin/server:52
    if (error) throw error
                     ^
Error: Timeout: PouchDB did not start after 10000ms.
    at null._onTimeout (kazana/node_modules/spawn-pouchdb-server/index.js:61:16)
    at Timer.listOnTimeout (timers.js:119:15)

```

It would be nice if that timeout would be configurable.

**Comment by gr2m** [comment]
related: it's configurable with `options.timeout` in ms, see https://github.com/hoodiehq/spawn-pouchdb-server/issues/11

**Comment by jo** [comment]
Yes, I know but how can this be done from a kazana app?

**Comment by jo** [comment]
I think this has been done by @gr2m

**Comment by gr2m** [comment]
Yes, for the record, the config is `backend.timeout`, it defaults to 30s
