### ISSUE TITLE
Allow replacing/disabling core module APIs

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#72]
Some kazana based apps need to offer permissions per group. @gr2m suggestion was to create a plugin `kazana-groups-raw-data` that offers that functionality. Problem is that the APIs from `kazana-raw-data` are still available since this is a core module, which is a security issue.

how to make these routes unavailable? One solution will be to allow replacing some core modules (`kazana-raw-data`) with other modules (`kazana-groups-raw-data`) or allowing disabling some core modules via config. Also, in this particular case maybe we can offer both `raw-data` handling options and allow plugins to select one via config?

**Comment by jo** [comment]
The *raw-data* database is an inherent part of Kazana, it is [bootstrapped in the core](https://github.com/eHealthAfrica/kazana/tree/master/bootstrap/raw-data). But not so `kazana-raw-data`, which just provides an http api for the database, besides any other possible interfaces (eg. `kazana-raw-data-ckan-bridge`).

Lets rename `kazana-raw-data` to `kazana-raw-data-api`. And make it optional.

- [ ] release breaking change major version of `kazana` without the plugin
- [ ] copy `kazana-raw-data` repo to `kazana-raw-data-api`
- [ ] write deprication note in `kazana-raw-data`
- [ ] update kazana apps

**Comment by gr2m** [comment]
I think there is no security issue with `kazana-raw-data`, you can only see submissions that you submitted yourself at this point

**Comment by jo** [comment]
That sounds good.

We probably need some authentication tests in `kazana-raw-data`

**Comment by patriciagarcia** [comment]
This is not needed for now, since polio scope has changed slightly (confirmed by @obdulia-losantos).
