### ISSUE TITLE
Transform of reports failing

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#78]
It used to work after restarting the service. Now, even when restarting the service not all documents are transformed.

Re: https://github.com/eHealthAfrica/polio-dashboard/issues/10

cc/ @jo @obdulia-losantos

**Comment by gr2m** [comment]
How urgent is this right now? I'm still catching up and there are a few kazana-related blockers I want to help with, so need help to set priorities :)

**Comment by obdulia-losantos** [comment]
It's not urgent. @jo was going to take care of it next week.

**Comment by jo** [comment]
See https://github.com/eHealthAfrica/polio-dashboard/issues/10#issuecomment-153746330.

Changed the first array entry to match the key:
- [ ] https://github.com/eHealthAfrica/van-transformer-excel-zone-dashboard
- [ ] https://github.com/eHealthAfrica/van-transformer-excel-state-dashboard
- [x] https://github.com/eHealthAfrica/polio-surveillance
- [x] https://github.com/eHealthAfrica/polio-intra-campaign
- [x] https://github.com/eHealthAfrica/polio-pre-campaign
- [x] https://github.com/eHealthAfrica/polio-post-campaign-lqas

**Comment by patriciagarcia** [comment]
@jo, can you take care of integrating this into van?

**Comment by jo** [comment]
@patriciagarcia yes, I did pulls for also for VAN yesterday:

- https://github.com/eHealthAfrica/van-transformer-excel-state-dashboard/pull/22
- https://github.com/eHealthAfrica/van-transformer-excel-zone-dashboard/pull/3

**Comment by lucychambers** [comment]
For the sake of documentation on this thread: This is top priority for VAN. Polio not affected. 

@jo Just checked in with @lucidNTR. Two things: 

1) Could you possibly elaborate on what each pull should be doing? 
2) We think that this has not fixed the issue for VAN as they were merged and Adam was still having issues. 

@adamvert - could you detail here the issues you were having and we can ask Johannes to look into it in more detail. cc @patriciagarcia

**Comment by jo** [comment]
This is not resolved yet.

Errors look like this:
```
Err! log  2015-11-16T16:34:31.475Z [ 'van-transformer-excel-state-dashboard',
Err! log   'excel-state-dashboard',
Err! log   'katsina-2015-10-05' ] { [Error: ESOCKETTIMEDOUT] status: 400 }
```

**Comment by jo** [comment]
Resolved by increasing the timeout. But we need to retry transformations: https://github.com/eHealthAfrica/kazana-transform/issues/8

**Comment by jo** [comment]
Finally resolved by changing to sequencial processing

**Comment by adamvert** [comment]
🎉

**Comment by obdulia-losantos** [comment]
:tada: :tada: :tada: :tada:

**Comment by gr2m** [comment]
wooohooo great joh @jo :+1:
