### ISSUE TITLE
Remove bundle bump bot from kazana repos

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#87]
Bundle bump bot has been replaced by Greenkeeper ranges functionality, right?
https://medium.com/greenkeeper-blog/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77

**Comment by jo** [comment]
>  remove it from dependencies and from "postsemantic-release": "bundle-bump-bot -u eHealthAfrica -r kazana"

**Comment by patriciagarcia** [comment]
@gr2m, @jo, I can't see `bundle-bump-bot` in any repo anymore. Does that mean it was removed already? (not sure if it was removed from "postsemantic-release" everywhere)

**Comment by gr2m** [comment]
yes, I removed it as part of https://github.com/eHealthAfrica/kazana/issues/102
