### ISSUE TITLE
[auth] kazana 7.0.1, admin gets a 401

### ISSUE THREAD

**Issue by obdulia-losantos** [eHealthAfrica/kazana#92]
The admin user in `polio` triggers this error:

```
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "User not authenticated"
}
```

@patriciagarcia

**Comment by patriciagarcia** [comment]
Could it be related to https://github.com/eHealthAfrica/kazana/issues/126?

**Comment by obdulia-losantos** [comment]
Could be, but this error didn't reproduce again. I think you can close this issue and if it happens again we'll reopen it.
