### ISSUE TITLE
pouchdb server behaves differently from couchbd

### ISSUE THREAD

**Issue by lucidNTR** [eHealthAfrica/kazana#97]
- random get errors when reading document with large attachment
- requests involving attachments take double the time or more often
- random timouts

**Comment by gr2m** [comment]
Can you please make reproduce able test cases so we can look into them one by one?

If this is blocking, you can set `backend.name` to `"couchdb"` and `backend.location` to `"http://user:password@localhost:1234"`. 

To make this a default for kazana apps you are working on locally, create `~/.kazanarc` with 

```
[backend]
  name=couchdb
  location=http://user:password@localhost:1234
```

Does that work as a workaround for the time being?

**Comment by lucidNTR** [comment]
@gr2m reproducible tests: no because its random and the performance issues could just be shown with performance measurement.

i know its easy to reconfigure, but the issue is that the standard should just be as close to production as possible and not a js reimplementation of the actual database.

I spend 1 day figuring out that pouchdb server is unreliable and the bugs were not my fault and this will randomly happen to other developers as well.

**Comment by jo** [comment]
I am celebrating that pouchdb server default and I'm sad to hear it made you such problems. I did not run into related issues but have to admit that I did not use large attachments yet.

Could you please fill an issue [on pouchdb-server](https://github.com/pouchdb/pouchdb-server/issues) or [on express-pouchdb](https://github.com/pouchdb/express-pouchdb/issues) with a little more information?

**Comment by lucidNTR** [comment]
@jo after this sprint i can try to reproduce the error with pure pouchdb server and file tickets there...

**Comment by jo** [comment]
Thanks :100: happy to help :rocket:

**Comment by gr2m** [comment]
Please create follow up issues as they occur.
